spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/dipendenti
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'